simplify sparc specific bits, this actually works (mostly)

diff --git a/anaconda-11.4.0.83-more-sparc-fixes.patch b/anaconda-11.4.0.83-more-sparc-fixes.patch
--- a/anaconda-11.4.0.83-more-sparc-fixes.patch
+++ b/anaconda-11.4.0.83-more-sparc-fixes.patch
@@ -1,7 +1,46 @@
+diff -up anaconda-11.4.0.83/bootdisk/sparc/silo.conf.spot anaconda-11.4.0.83/bootdisk/sparc/silo.conf
+--- anaconda-11.4.0.83/bootdisk/sparc/silo.conf.spot	2008-10-04 11:12:37.000000000 -0400
++++ anaconda-11.4.0.83/bootdisk/sparc/silo.conf	2008-10-04 11:12:10.000000000 -0400
+@@ -2,20 +2,20 @@ partition=1
+ default=linux
+ read-write
+ timeout=100
+-message=/etc/boot.msg
+-image="cat /etc/boot.msg"
++message=/boot/boot.msg
++image="cat /boot/boot.msg"
+         label=1
+         single-key
+-image="cat /etc/options.msg"
++image="cat /boot/options.msg"
+         label=2
+         single-key
+-image="cat /etc/general.msg"
++image="cat /boot/general.msg"
+         label=3
+         single-key
+-image="cat /etc/param.msg"
++image="cat /boot/param.msg"
+         label=4
+         single-key
+-image="cat /etc/rescue.msg"
++image="cat /boot/rescue.msg"
+         label=5
+         single-key
+ image[sun4u]=/boot/vmlinux
 diff -up anaconda-11.4.0.83/scripts/mk-images.sparc.spot anaconda-11.4.0.83/scripts/mk-images.sparc
 --- anaconda-11.4.0.83/scripts/mk-images.sparc.spot	2008-10-01 21:32:11.000000000 -0400
-+++ anaconda-11.4.0.83/scripts/mk-images.sparc	2008-10-03 14:59:44.000000000 -0400
-@@ -52,52 +52,51 @@ maketftp() {
++++ anaconda-11.4.0.83/scripts/mk-images.sparc	2008-10-04 11:44:50.000000000 -0400
+@@ -44,6 +44,8 @@ maketftp() {
+        exit 1
+     done
+ 
++    echo "Making a $KERNELARCH tftp image: $TFTPIMAGE"
++
+     elftoaout $TFTPKERNEL -o $TFTPIMAGE
+     if [ "$KERNELARCH" = "sparc" ]; then
+        piggyback $TFTPIMAGE $TFTPSYSMAP $TFTPINITRD
+@@ -52,51 +54,41 @@ maketftp() {
      fi
  }
  
@@ -9,6 +48,11 @@ diff -up anaconda-11.4.0.83/scripts/mk-images.sparc.spot anaconda-11.4.0.83/scri
 -	echo "sparc: prepareBootImage() is called"
 +prepareBootTree() {
 +	echo "sparc: prepareBootTree() is called"
++	(cd $BOOTDISKDIR; find . -maxdepth 1 ! -type d | cpio --quiet -p $MBD_BOOTTREE)
++
++	cp $MBD_FSIMAGE $MBD_BOOTTREE/initrd.img
++	cp $KERNELROOT/boot/vmlinuz-* $MBD_BOOTTREE/vmlinuz
++	cp $KERNELROOT/boot/System.map-* $MBD_BOOTTREE/System.map
  
 -        dd if=/dev/zero of=$MBD_TMPIMAGE bs=1k count=$BOOTDISKSIZE 2>/dev/null
 -        echo y | /sbin/mke2fs -b 1024 -r 0 -O none $MBD_TMPIMAGE  > /dev/null 2>/dev/null
@@ -24,22 +68,6 @@ diff -up anaconda-11.4.0.83/scripts/mk-images.sparc.spot anaconda-11.4.0.83/scri
 -	losetup -d $LODEV
 -	mount -o loop -t ext2 $MBD_TMPIMAGE $MBD_BOOTTREE
 -	$SILO -r $MBD_BOOTTREE -i /fd.b -b /second.b -C /etc/silo.conf -F
-+	mkdir -p $MBD_BOOTTREE/../etc/	
-+	cp $BOOTDISKDIR/*.msg $MBD_BOOTTREE/../etc/ 
-+	cp $KERNELROOT/boot/vmlinuz-* $MBD_BOOTTREE/vmlinuz
-+	cp $KERNELROOT/boot/System.map-* $MBD_BOOTTREE/System.map
-+
-+	cp $BOOTDISKDIR/silo.conf $MBD_BOOTTREE/
-+
-+	# silo files
-+	if [ -f $IMGPATH/boot/second.b ]; then
-+		cp $IMGPATH/boot/second.b $MBD_BOOTTREE/
-+		cp $IMGPATH/boot/fd.b $MBD_BOOTTREE/
-+		cp $IMGPATH/boot/isofs.b $MBD_BOOTTREE/		
-+	else
-+		echo "Cannot find SILO files!"
-+		exit 1
-+	fi
  }
  
  makeBootImages() {
@@ -56,33 +84,41 @@ diff -up anaconda-11.4.0.83/scripts/mk-images.sparc.spot anaconda-11.4.0.83/scri
 -    mkdir -p $TOPDESTPATH/kernels
 -    cp $KERNELROOT/boot/vmlinuz-* $TOPDESTPATH/kernels/vmlinux
 -    cp $KERNELROOT/boot/System.map-* $TOPDESTPATH/boot/System.map
-+    MBD_BOOTTREE=$TOPDESTPATH/boot
-+    MBD_FSIMAGE=$TOPDESTPATH/boot/initrd.img
-+    
-+    mkdir -p $MBD_BOOTTREE
- 
-     echo "List of init modules: $INITRDMODS $SPARCMODS"
- 
+-
+-    echo "List of init modules: $INITRDMODS $SPARCMODS"
+-
 -    makeinitrd --initrdto $TOPDESTPATH/boot/initrd.img \
-+    makeinitrd --initrdto $MBD_FSIMAGE \
++    echo "Building initrd.img"
++    makeinitrd --initrdto $TOPDESTPATH/images/initrd.img \
  	--initrdsize 8192 \
  	--loaderbin loader \
  	--modules "$INITRDMODS $SPARCMODS"
- 
-+    prepareBootTree
-+
-     maketftp --kernel $TOPDESTPATH/boot/vmlinux \
- 	--imagename $TOPDESTPATH/images/tftp.img \
+-
+-    maketftp --kernel $TOPDESTPATH/boot/vmlinux \
+-	--imagename $TOPDESTPATH/images/tftp.img \
 -	--initrdfrom $TOPDESTPATH/boot/initrd.img \
-+	--initrdfrom $MBD_FSIMAGE \
- 	--systemmap $TOPDESTPATH/boot/System.map
- 
-+    echo "List of init modules: $INITRDMODS $SPARCMODS"
+-	--systemmap $TOPDESTPATH/boot/System.map
++    [ $? = 0 ] || exit 1
++    if [ -f $IMGPATH/usr/lib/anaconda-runtime/boot/second.b ]; then
++	echo "Building boot dir for silo"
++	MBD_BOOTTREE=$TOPDESTPATH/boot
++	MBD_FSIMAGE=$TOPDESTPATH/images/initrd.img
++	mkdir $MBD_BOOTTREE
++	cp $IMGPATH/usr/lib/anaconda-runtime/boot/*.b $MBD_BOOTTREE/
++	
++	prepareBootTree
 +
++	maketftp --kernel $MBD_BOOTTREE/vmlinuz \
++		 --imagename $TOPDESTPATH/images/tftp.img \
++		 --systemmap $MBD_BOOTTREE/System.map
++    else
++	echo "I can't find SILO in $IMGPATH/usr/lib/anaconda-runtime/boot ?!?"
++	exit 1
++    fi
+ 
  }
  
- doPostImages() {
-@@ -110,6 +109,8 @@ doPostImages() {
+@@ -110,6 +102,8 @@ doPostImages() {
  			-r -V "PBOOT" -A "$PRODUCT $VERSION" \
  			-x Fedora \
  			-x repodata \
